version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: 16G
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
